# Generated by Django 5.1.7 on 2025-04-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(default=dict),
        ),
    ]
