# Generated by Django 5.1.7 on 2025-04-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='company_name',
            new_name='company',
        ),
    ]
